multiple updates to both approaches to containerized bigip

diff --git a/bigip/k8s-direct/v_cloud_init.template b/bigip/k8s-direct/v_cloud_init.template
--- a/bigip/k8s-direct/v_cloud_init.template
+++ b/bigip/k8s-direct/v_cloud_init.template
@@ -12,21 +12,15 @@ write_files:
   #  encoding: b64
   #  content: ${userAlert}
 
-  #- path: /shared/rebind_eth0_driver
-  #  permissions: 0755
-  #  encoding: b64
-  #  content: ${rebindNicDriver}
+  - path: /shared/rebind_eth0_driver
+    permissions: 0755
+    encoding: b64
+    content: ${rebindNicDriver}
 
-  #- path: /config/tmm_init.tcl
-  #  permissions: 0644
-  #  content: |
-  #    device driver vendor_dev 15b3:101e mlxvf5
-  #    #device driver pci 06:00.0 mlxvf5
-  #    #device driver pci 07:00.0 xnet
-  #    #device driver pci 07:00.0 dpdk
-  #    #device driver vendor_dev 15b3:101e xnet
-  #    #ndal rx_devq_sz 512 15b3:101e
-  #    #ndal tx_devq_sz 512 15b3:101e
+  - path: /config/tmm_init.tcl
+    permissions: 0644
+    content: |
+      device driver vendor_dev 15b3:101e mlxvf5
 
   - path: /shared/cloud_init.bash
     permissions: 0755
@@ -38,57 +32,87 @@ write_files:
       # source wait_bigip_ready* functions
       source /usr/lib/bigstart/bigip-ready-functions
 
-      # Declare bash arrays for various configuration elements
+      ### Static variables
+      podInfo="/run/kv-annotations"
+      annotations="$podInfo/annotations"
+
+      # config-map containing ltm config variables
       declare -A config
       declare -A mac_map
       declare -A interfaces
+      ltmInfo="/run/kv-ltm"
 
       # Hardcode config elements to work-around the lack of config-maps in AODS
-      # System-wide variables
       config[hostname]="${hostname}"
       config[dnsServers]="${dnsServers}"
       config[ntpServers]="${ntpServers}"
       config[ntpTimezone]="${ntpTimezone}"
-      config[strictpasswords]="${strictPasswords}"
-      config[sshPort]="${sshPort}"
-      config[regKey]="${regKey}"
-      config[pubKey]="${pubKey_b64}"
-      config[rebindNicScript]="${rebindNicDriver}"
-      config[userAlert]="${userAlert}"
-      config[envFile]="${envFile}"
-      config[proxyProtocol]="${proxyProtocol}"
-      config[proxyAddr]="${ProxyAddr}"
-      config[proxyPort]="${ProxyPort}"
-      # Management (CSN) networking
-      config[mgmtAddr]="${csnV4addr}"
-      config[mgmtCidr]="${csnV4cidr}"
-      config[mgmtGtwy]="${csnV4gtwy}"
-      # OAM networking
-      config[dataVlanName1]="${oamName}"
-      config[dataVlanAddr1]="${oamV4addr}"
-      config[dataVlanCidr1]="${oamV4cidr}"
-      config[dataVlanTag1]="${oamVlanTag}"
-      config[dataVlanMac1]="${oamMacAddr}"
-      # Client networking
-      config[dataVlanName2]="${clientName}"
-      config[dataVlanAddr2]="${clientV4addr}"
-      config[dataVlanCidr2]="${clientV4cidr}"
-      config[dataVlanTag2]="${clientVlanTag}"
-      config[dataVlanMac2]="${clientMacAddr}"
-      # Server networking
-      config[dataVlanName3]="${serverName}"
-      config[dataVlanAddr3]="${serverV4addr}"
-      config[dataVlanCidr3]="${serverV4cidr}"
-      config[dataVlanTag3]="${serverVlanTag}"
-      config[dataVlanMac3]="${serverMacAddr}"
+      config[mgmtAddr]="${mgmtAddr}"
+      config[mgmtCidr]="${mgmtCidr}"
+      config[mgmtGtwy]="${mgmtGtwy}"
+      config[dataVlanName1]="${dataVlanName1}"
+      config[dataVlanTag1]="${dataVlanTag1}"
+      config[dataVlanAddr1]="${dataVlanAddr1}"
+      config[dataVlanCidr1]="${dataVlanCidr1}"
+      #config[dataVlanMac1]="${dataVlanMac1}"
       config[dataGtwy]="${dataGtwy}"
+      config[dataVlanName2]="${dataVlanName2}"
+      config[dataVlanTag2]="${dataVlanTag2}"
+      config[dataVlanAddr2]="${dataVlanAddr2}"
+      config[dataVlanCidr2]="${dataVlanCidr2}"
+      #config[dataVlanMac2]="${dataVlanMac2}"
+      config[adminPass]="${adminPass}"
+      config[rootPass]="${rootPass}"
+      config[proxyProtocol]="${proxyProtocol}"
+      config[strictpasswords]="${strictpasswords}"
+      config[pubKey]="${pubKey}"
+      config[envFile]="${envFile}"
+      config[proxyAddr]="${proxyAddr}"
+      config[proxyPort]="${proxyPort}"
+      config[regKey]="${regKey}"
 
+
+      # cloud-init output location for review/troubleshooting
+      ciDir="/shared/cloud_init"
 
       ###
       ### Functions
       ###
 
-      ## Get BIG-IP configuration elements
+      # Mount disks with pod annotations and config-map with ltm config
+      function mount_podinfo() {
+        # Create and mount pod annotations and bigip_v1515 config-map
+        if [[ ! -d $podInfo ]]; then mkdir $podInfo; fi
+        mount /dev/vdc $podInfo #2>/dev/null
+        if [[ $? != 0 ]]; then
+          echo "$(date +%T) Attempt to mount /dev/vdc to $podInfo failed"
+        fi
+      }
+
+      # Unmount pod annotations
+      function unmount_podinfo() {
+        echo "$(date +%T) Unmounting $podInfo and $ltmInfo"
+        # Unmount and delete podinfo directory
+        umount $podInfo; rmdir $podInfo
+        umount $ltmInfo; rmdir $ltmInfo
+        echo "$(date +%T) $podInfo and $ltmInfo now unmounted"
+      }
+
+      # Craete cloud-init info location
+      function create_ci_dir() {
+        # Create cloud_init dir, link to /root/, and output variable values
+        if [[ ! -d $ciDir ]]; then
+          mkdir /shared/cloud_init
+          ln -s /shared/cloud_init /root/cloud_init
+        else
+          rm -rf $ciDir/*
+        fi
+
+        # copy this script to cloud_init location for troubleshooting
+        cp $0 $ciDir/cloud_init.bash && chmod 755 $ciDir/cloud_init.bash
+      }
+
+      # Get BIG-IP configuration elements
       #function get_ltm_cfg() {
       #  if [[ -d $ltmInfo ]]; then
       #    for k in $(ls -1 $ltmInfo); do
@@ -99,7 +123,7 @@ write_files:
       #    echo "$(date +%T) Successfully sourced $ltmInfo"
       #    test -f /shared/config-map.txt && rm /shared/config-map.txt
       #    for k in ${!config[*]}; do
-      #      printf "%20s -> %20s\\n" $k ${config[$k]} >> /shared/config-map.txt
+      #      printf "%20s -> %20s\n" $k ${config[$k]} >> /shared/config-map.txt
       #    done
       #    echo "$(date +%T) config-map contents written to /shared/config-map.txt"
       #  else
@@ -126,24 +150,36 @@ write_files:
         echo "/shared" >> /config/ssh/scp.whitelist
         tmsh restart sys service sshd
 
-      # If ssh port is not 22, update to the defined value
-      if [[ ${config[sshPort]} != 22 ]]; then tmsh modify sys ssh port ${config[sshPort]}; fi
-
-
         if [[ ${config[strictpasswords]} == "disable" ]]; then
           echo "$(date +%T) Disabling strict password policy"
           tmsh modify sys db users.strictpasswords value ${config[strictpasswords]}
         fi
       }
 
+      # Change admin password 
+      function update_credentials() {
+        # admin user
+        if [[ -n ${config[adminPass]} ]]; then
+          echo "$(date +%T) Updating admin password"
+          tmsh modify auth user admin shell bash password ${config[adminPass]}
+        fi
+
+        # root user
+        if [[ -n ${config[rootPass]} ]]; then
+          echo "$(date +%T) Updating root password"
+          echo ${config[rootPass]} | awk '{printf "%s\n%s\n", $1, $1}' | tmsh modify auth password root
+        fi
+
+      }
+
       # Add $sshKey to admin and root
       function inject_pubkey() {
         if [[ -n ${config[pubKey]} ]]; then
-          pubKey=$(printf "%s" ${config[pubKey]} | base64 -d)
+          pubKey=$(echo ${config[pubKey]} | base64 -d)
           echo "$(date +%T) Found ssh public key; adding to authorized_keys"
           echo "$(date +%T) Key: $pubKey"
-          echo "$pubKey" >> /var/ssh/root/authorized_keys
-          #echo "$pubKey" >> /home/admin/.ssh/authorized_keys
+          echo "${config[pubKey]}" | base64 -d >> /var/ssh/root/authorized_keys
+          echo "${config[pubKey]}" | base64 -d >> /home/admin/.ssh/authorized_keys
         else
           echo "$(date +%T) Skipping SSH public key insertion, config[pubKey] not defined"
         fi
@@ -163,7 +199,7 @@ write_files:
           tmsh create sys management-route default gateway ${config[mgmtGtwy]}
         fi
       }
-
+      
       # create vlans based on mac-addresses provided in the config-map
       function create_dataplane_by_mac() {
         # Find all nics
@@ -212,8 +248,8 @@ write_files:
             imac=$(echo ${interfaces[$i]} | tr -d ':.' | tr [:upper:] [:lower:])
             test $DEBUG && echo "$(date +%T) interface: $i, mac: $imac"
             if [[ ${imac#0} =~ ${vlan_mac#0} ]]; then
-              test $DEBUG && echo "$(date +%T) Associating interface $i (mac: $imac) with index $id (${config[dataVlanMac\${id}]})"
-              mac_map[${imac}]=\${id}
+              test $DEBUG && echo "$(date +%T) Associating interface $i (mac: $imac) with index $id (${config[dataVlanMac${id}]})"
+              mac_map[${imac}]=${id}
               break
             fi
           done
@@ -227,20 +263,20 @@ write_files:
           # Make sure this mac exists in the mac_map array
           if [[ ${mac_map[$mac]} == "" ]]; then continue; fi
           id=${mac_map[$mac]}
-          vlanAddr=${config[dataVlanAddr\${id}]}
-          vlanCidr=${config[dataVlanCidr\${id}]}
-          vlanMac=${config[dataVlanMac\${id}]}
+          vlanAddr=${config[dataVlanAddr${id}]}
+          vlanCidr=${config[dataVlanCidr${id}]}
+          vlanMac=${config[dataVlanMac${id}]}
 
           # Define vlan name if none provided
-          if [[ -n ${config[dataVlanName\${id}]} ]]; then
-            vlanName=${config[dataVlanName\${id}]}
+          if [[ -n ${config[dataVlanName${id}]} ]]; then
+            vlanName=${config[dataVlanName${id}]}
           else
             vlanName=$(printf "vlan%03d" $id)
           fi
 
           # Define vlan name if none provided
-          if [[ -n ${config[dataVlanTag\${id}]} ]]; then
-            vlanTag=${config[dataVlanTag\${id}]}
+          if [[ -n ${config[dataVlanTag${id}]} ]]; then
+            vlanTag=${config[dataVlanTag${id}]}
           else
             vlanTag=$((4000 + $id))
           fi
@@ -263,18 +299,16 @@ write_files:
         nics=$(tmsh show net interface | awk '/^1/ { print $1 }' | cut -d. -f2)
 
         for n in $nics; do
-          if [[ $n == 0 ]]; then continue; fi
-
           # Define vlan name if none provided
-          if [[ -n ${config[dataVlanName\${n}]} ]]; then
-            vlanName=${config[dataVlanName\${n}]}
+          if [[ -n ${config[dataVlanName${n}]} ]]; then
+            vlanName=${config[dataVlanName${n}]}
           else
             vlanName=$(printf "vlan%04d" $n)
           fi
 
           # Define vlan tag if none provided
-          if [[ -n ${config[dataVlanTag\${n}]} ]]; then
-            vlanTag=${config[dataVlanTag\${n}]}
+          if [[ -n ${config[dataVlanTag${n}]} ]]; then
+            vlanTag=${config[dataVlanTag${n}]}
           else
             vlanTag=$((4000 + $n))
           fi
@@ -283,9 +317,9 @@ write_files:
           test $DEBUG && echo "tmsh create net vlan $vlanName tag $vlanTag interfaces add { 1.$n }"
           tmsh create net vlan $vlanName tag $vlanTag interfaces add { 1.$n }
 
-          echo "Assigning self-ip ${config[dataVlanAddr\${n}]} to vlan $vlanName"
-          test $DEBUG && echo "tmsh create net self ${config[dataVlanAddr\${n}]}/${config[dataVlanCidr\${n}]} vlan $vlanName"
-          tmsh create net self ${config[dataVlanAddr\${n}]}/${config[dataVlanCidr\${n}]} vlan $vlanName
+          echo "Assigning self-ip ${config[dataVlanAddr${n}]} to vlan $vlanName"
+          test $DEBUG && tmsh create net self ${config[dataVlanAddr${n}]}/${config[dataVlanCidr${n}]} vlan $vlanName
+          tmsh create net self ${config[dataVlanAddr${n}]}/${config[dataVlanCidr${n}]} vlan $vlanName
         done
       }
 
@@ -299,44 +333,15 @@ write_files:
           tmsh create net route default gw ${config[dataGtwy]}
         fi
       }
-      
+
       # Enable managment access to first vlan self-ip
       function enable_mgmt_access() {
         # Allow SSH and management on first self-ip
         if [[ ${config[dataVlanAddr1]} ]]; then
           echo "$(date +%T) Enabling SSH and HTTPS access to first data-plane IP address"
-          test $DEBUG && echo "tmsh modify net self ${config[dataVlanAddr1]}/${config[dataVlanCidr1]} allow-service add { tcp:443 tcp:${config[sshPort]} }"
-          tmsh modify net self ${config[dataVlanAddr1]}/${config[dataVlanCidr1]} allow-service add { tcp:443 tcp:${config[sshPort]} }
+          test $DEBUG && echo "tmsh modify net self ${config[dataVlanAddr1]}/${config[dataVlanCidr1]} allow-service add { tcp:443 tcp:22 }"
+          tmsh modify net self ${config[dataVlanAddr1]}/${config[dataVlanCidr1]} allow-service add { tcp:443 tcp:22 }
         fi
-      }
-
-      # Bind eth0 to mlx5_core driver
-      # This is reset every time TMM is restarted, so we will need a better long-term solution
-      function bind_mgmt_interface() {
-        # Identify first interface PCI address
-        echo "$(date +%T) Finding first network interface for use with CSN"
-        pci_addr="0000:$(lspci | grep -m1 Mellanox | awk '{ print $1 }')"
-        echo "$(date +%T) Found PCI addrss $pci_addr"
-
-        # Add driver override entry
-        echo "$(date +%T) Overriding driver for pci: $pci_addr"
-        [[ $DEBUG ]] && echo "$(date +%T) echo mlx5_core > /sys/bus/pci/devices/\${pci_addr}/driver_override"
-        echo mlx5_core > /sys/bus/pci/devices/\${pci_addr}/driver_override
-
-        # forcibly probe that PCI slot
-        echo "$(date +%T) Probing pci address: $pci_addr"
-        [[ $DEBUG ]] && echo "$(date +%T) echo $pci_addr > /sys/bus/pci/drivers/drivers_probe"
-        echo $pci_addr > /sys/bus/pci/drivers_probe
-
-        # Add eth0 to mgmt bridge
-        echo "$(date +%T) Adding interface eth0 to mgmt bridge"
-        [[ $DEBUG ]] && echo "$(date +%T) brctl addif mgmt eth0"
-        brctl addif mgmt eth0
-
-        # Enable interface
-        echo "$(date +%T) Enabling interface eth0"
-        [[ $DEBUG ]] && echo "$(date +%T) ifconfig eth0 up"
-        ifconfig eth0 up
       }
 
 
@@ -371,19 +376,21 @@ write_files:
       function activate_license() {
         if [[ -n ${config[regKey]} ]]; then
           echo "$(date +%T) Attempting to activate license: ${config[regKey]}"
-          if [[ -n ${config[proxyAddr]} && -n ${config[proxyPort]} ]]; then
-            echo "$(data +%T) Running SOAPLicenseClient with proxy: ${config[proxyAddr]}:${config[proxyPort]}"
-            test $DEGUB && echo "SOAPLicenseClient --proxy ${config[proxyAddr]}:${config[proxyPort]} --basekey ${config[regKey]}"
-            SOAPLicenseClient --proxy ${config[proxyAddr]}:${config[proxyPort]} --basekey ${config[regKey]}
+          if [[ -n ${config[proxyAddr]} && -n ${config[proxyPort]} && -n ${config[proxyProtocol]} ]]; then
+            echo "$(data +%T) Proxy: ${config[proxyAddr]}:${config[proxyPort]}"
+            echo "SOAPLicenseClient --proxy ${config[proxyProtocol]}://${config[proxyAddr]}:${config[proxyPort]} --basekey ${config[regKey]}"
+            SOAPLicenseClient --proxy ${config[proxyProtocol]}://${config[proxyAddr]}:${config[proxyPort]} --basekey ${config[regKey]}
           else
-            echo "$(date +%T) Running SOAPLicenseClient without proxy"
-            test $DEBUG && echo "SOAPLicenseClient --basekey ${config[regKey]}"
+            echo "$(date +%T) Not using proxy"
+            echo "SOAPLicenseClient --basekey ${config[regKey]}"
             SOAPLicenseClient --basekey ${config[regKey]}
           fi
         else
-          echo "$(date +%T) No Registration key defined, skipping license activation"
+          echo "$(date +%T) RegKey not defined, skipping license activation"
         fi
       }
+
+
 
       ###
       ### Main
@@ -392,18 +399,27 @@ write_files:
       # Source bigip ready functions
       source /usr/lib/bigstart/bigip-ready-functions
       # Wait for bigip to be ready to execute
-      echo "$(date +%T) Waiting for BIG-IP to reach ready state"
       wait_bigip_ready
       echo "$(date +%T) wait_bigip_ready() returned, proceeding with configuration"
       
-      # Create tmm_init.tcl and restart tmm
-      create_tmm_init
-      tmsh save sys config >/dev/null 2>&1
+      # Create cloud-init dir for troubleshooting
+      create_ci_dir
 
+      ## Mount podinfo volume
+      #mount_podinfo
+      ## Get pod network address
+      #get_pod_addr
+      ## unmount podinfo volume
+      #unmount_podinfo
+
+
+      # Create tmm_init.tcl and restart tmm
       update_global
       assign_mgmt_addr
       inject_pubkey
+      update_credentials
       mk_cli_env
+      create_tmm_init
 
       # If interface mac-addresses were provided in config-map, assign interfaces to vlans
       # based on their mac address. Otherwise, assign interfaces based on presentation order.
@@ -420,17 +436,12 @@ write_files:
 
       # Save configuration
       echo "$(date +%T) Saving configuration"
-      tmsh save sys config >/dev/null 2>&1
-
-      # Restart TMM to ensure it reads the /config/tmm_init.tcl
-      #echo "$(date +%T) Restarting TMM"
-      #test $DEBUG && echo "tmsh restart sys service tmm"
-      #tmsh restart sys service tmm
+      tmsh save sys config
 
       # Activate license
-      #activate_license
+      activate_license
 
-runcmd:
-  - /shared/cloud_init.bash &
+
+runcmd: [nohup sh -c '/shared/cloud_init.bash' &]
 
 # vim: set syntax=bash tabstop=2 expandtab:
